id: P006954
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11728
  title: དགེ་འདུན་ཉི་ཤུའི་མཐའ་དཔྱོད་སྐལ་བཟང་འཇུག་ངོགས་སོགས།
  author: ''
  volumes:
    0e1a74a0fe454b47b75859bee87fa1c1:
      image_group_id: I1KG11743
      title: Volume 1 of dge 'dun nyi shu'i mtha' dpyod skal bzang 'jug ngogs sogs/
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
ebook_metadata:
  title: དགེ་འདུན་ཉི་ཤུའི་མཐའ་དཔྱོད་སྐལ་བཟང་འཇུག་ངོགས་སོགས།
  author: ''
  sku: P006954
  cover: cover.jpg
  layers:
  - pagination
