id: P006954
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11728
  title: དགེ་འདུན་ཉི་ཤུའི་མཐའ་དཔྱོད་སྐལ་བཟང་འཇུག་ངོགས་སོགས།
  author: ''
  volumes:
    7dc6eaa2ff6746e7be66f72d026f1037:
      image_group_id: I1KG11743
      title: ''
      volume_number: 1
      total_pages: 294
ebook_metadata:
  title: དགེ་འདུན་ཉི་ཤུའི་མཐའ་དཔྱོད་སྐལ་བཟང་འཇུག་ངོགས་སོགས།
  author: ''
  sku: P006954
  cover: cover.jpg
  layers:
  - pagination
