id: I1C026A8C
legacy_id: P006954
ocr_import_info:
  bdrc_scan_id: W1KG11728
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T02:51:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:02:57.548104+00:00'
last_modified: 2022-08-31 11:03:07.457116
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11728
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11728
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་འདུན་ཉི་ཤུའི་མཐའ་དཔྱོད་སྐལ་བཟང་འཇུག་ངོགས་སོགས།
  author: བསེ་ཚང ༠༡་ངག་དབང་བཀྲ་ཤིས།
statistics:
  ocr_word_mean_confidence_index: 0.6558732174451987
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1KG11743:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11743
      total_pages: 294
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11743.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6558732174451987
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
