id: I1C026A8C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T02:53:22+00:00'
last_modified: '2022-06-08T12:54:57.237204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11728
  title: དགེ་འདུན་ཉི་ཤུའི་མཐའ་དཔྱོད་སྐལ་བཟང་འཇུག་ངོགས་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC5F:
      image_group_id: I1KG11743
      title: Volume 1 of dge 'dun nyi shu'i mtha' dpyod skal bzang 'jug ngogs sogs/
      total_pages: 294
      order: 1
      base_file: CC5F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
